name: predict-new-data

# This action will trigger the predictions at minute 0 past every 6th hour.
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Prepare environment
        run: |
          pip install pipenv
          pipenv lock --keep-outdated --requirements > requirements.txt
          pip install -r requirements.txt

      - name: Predict and retrain
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL}}
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          WANDB_PROJECT: ${{ secrets.WANDB_PROJECT }}
          MODEL_REGISTRY: ${{ secrets.MODEL_REGISTRY }}
          MODEL: ${{ secrets.MODEL }}
        run: |
          mkdir output
          python src/model_predict.py
